# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  
    # AmountType - The amount type of the deduction for the pay period.
    class AmountType < T::Enum
      enums do
        FIXED = new('fixed')
        PERCENT = new('percent')
      end
    end
  end
end
