# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  
    # BlockerType - The type of blocker
    class BlockerType < T::Enum
      enums do
        MINIMUM_DAYS = new('minimum_days')
        MINIMUM_FUNDED_PAYMENTS = new('minimum_funded_payments')
      end
    end
  end
end
