# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  
    # A Bureau of Labor Statistics occupation code with its title and description, used for salary estimate calculations.
    class BLSOccupation < ::Crystalline::FieldAugmented
      extend T::Sig

      # Bureau of Labor Statistics (BLS) occupation code.
      field :code, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('code') } }
      # Occupation title.
      field :title, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('title') } }
      # Occupation description.
      field :description, T.nilable(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('description') } }


      sig { params(code: ::String, title: ::String, description: T.nilable(::String)).void }
      def initialize(code: nil, title: nil, description: nil)
        @code = code
        @title = title
        @description = description
      end
    end
  end
end
