# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
    
      # The representation of compensation in Gusto.
      class Compensation
        extend T::Sig
        include Crystalline::MetadataFields

        # The UUID of the compensation in Gusto.
        field :uuid, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('uuid'), required: true } }
        # The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
        field :version, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('version') } }
        # The UUID of the job to which the compensation belongs.
        field :job_uuid, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('job_uuid') } }
        # The UUID of the employee to which the compensation belongs.
        field :employee_uuid, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('employee_uuid') } }
        # The dollar amount paid per payment unit.
        field :rate, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('rate') } }
        # The unit accompanying the compensation rate. If the employee is an owner, rate should be 'Paycheck'.
        field :payment_unit, Crystalline::Nilable.new(Models::Shared::PaymentUnit), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('payment_unit'), 'decoder': Utils.enum_from_string(Models::Shared::PaymentUnit, true) } }
        # The FLSA status for this compensation. Salaried ('Exempt') employees are paid a fixed salary every pay period. Salaried with overtime ('Salaried Nonexempt') employees are paid a fixed salary every pay period, and receive overtime pay when applicable. Hourly ('Nonexempt') employees are paid for the hours they work, and receive overtime pay when applicable. Commissioned employees ('Commission Only Exempt') earn wages based only on commission. Commissioned with overtime ('Commission Only Nonexempt') earn wages based on commission, and receive overtime pay when applicable. Owners ('Owner') are employees that own at least twenty percent of the company. 
        field :flsa_status, Crystalline::Nilable.new(Models::Shared::FlsaStatusType), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('flsa_status'), 'decoder': Utils.enum_from_string(Models::Shared::FlsaStatusType, true) } }
        # The effective date for this compensation. For the first compensation, this defaults to the job's hire date.
        field :effective_date, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('effective_date') } }
        # Indicates if the compensation could be adjusted to minimum wage during payroll calculation.
        field :adjust_for_minimum_wage, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('adjust_for_minimum_wage') } }
        # The minimum wages associated with the compensation.
        field :minimum_wages, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::MinimumWages)), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('minimum_wages') } }

        sig { params(uuid: ::String, version: T.nilable(::String), job_uuid: T.nilable(::String), employee_uuid: T.nilable(::String), rate: T.nilable(::String), payment_unit: T.nilable(Models::Shared::PaymentUnit), flsa_status: T.nilable(Models::Shared::FlsaStatusType), effective_date: T.nilable(::String), adjust_for_minimum_wage: T.nilable(T::Boolean), minimum_wages: T.nilable(T::Array[Models::Shared::MinimumWages])).void }
        def initialize(uuid:, version: nil, job_uuid: nil, employee_uuid: nil, rate: nil, payment_unit: nil, flsa_status: nil, effective_date: nil, adjust_for_minimum_wage: nil, minimum_wages: nil)
          @uuid = uuid
          @version = version
          @job_uuid = job_uuid
          @employee_uuid = employee_uuid
          @rate = rate
          @payment_unit = payment_unit
          @flsa_status = flsa_status
          @effective_date = effective_date
          @adjust_for_minimum_wage = adjust_for_minimum_wage
          @minimum_wages = minimum_wages
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @uuid == other.uuid
          return false unless @version == other.version
          return false unless @job_uuid == other.job_uuid
          return false unless @employee_uuid == other.employee_uuid
          return false unless @rate == other.rate
          return false unless @payment_unit == other.payment_unit
          return false unless @flsa_status == other.flsa_status
          return false unless @effective_date == other.effective_date
          return false unless @adjust_for_minimum_wage == other.adjust_for_minimum_wage
          return false unless @minimum_wages == other.minimum_wages
          true
        end
      end
    end
  end
end
