# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  
    # ContractorPaymentMethod1 - The contractor's payment method.
    class ContractorPaymentMethod1 < T::Enum
      enums do
        DIRECT_DEPOSIT = new('Direct Deposit')
        CHECK = new('Check')
      end
    end
  end
end
