# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  
    # ContractorPaymentForGroupPreviewStatus - The status of the contractor payment.  Will transition to `Funded` during payments processing if the payment should be funded, i.e. has `Direct Deposit` for payment method. Contractors payments with `Check` payment method will remain `Unfunded`.
    class ContractorPaymentForGroupPreviewStatus < T::Enum
      enums do
        FUNDED = new('Funded')
        UNFUNDED = new('Unfunded')
      end
    end
  end
end
