# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  

    class Deductions < ::Crystalline::FieldAugmented
      extend T::Sig


      field :amount, T.nilable(::Float), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('amount') } }

      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('name') } }


      sig { params(amount: T.nilable(::Float), name: T.nilable(::String)).void }
      def initialize(amount: nil, name: nil)
        @amount = amount
        @name = name
      end
    end
  end
end
