# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  
    # EmployeePayStubsListPaymentMethod - The payment method for the pay stub.
    class EmployeePayStubsListPaymentMethod < T::Enum
      enums do
        DIRECT_DEPOSIT = new('Direct Deposit')
        CHECK = new('Check')
      end
    end
  end
end
