# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared

      class EmployeeStateTaxInputQuestionFormat
        extend T::Sig
        include Crystalline::MetadataFields

        # Describes the type of question - Text, Number, Select, Currency, Date
        field :type, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('type'), required: true } }
        # For "Select" type questions, the allowed values and display labels.
        field :options, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::EmployeeStateTaxInputQuestionFormatOptions)), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('options') } }

        sig { params(type: ::String, options: T.nilable(T::Array[Models::Shared::EmployeeStateTaxInputQuestionFormatOptions])).void }
        def initialize(type:, options: nil)
          @type = type
          @options = options
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @options == other.options
          true
        end
      end
    end
  end
end
