# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared

      class Errors
        extend T::Sig
        include Crystalline::MetadataFields

        # Error key
        field :error_key, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('error_key') } }
        # Error category
        field :category, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('category') } }
        # Blocker message
        field :message, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('message') } }

        field :metadata, Crystalline::Nilable.new(Models::Shared::PartnerManagedCompanyMigrationReadinessResponseMetadata), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('metadata') } }

        sig { params(error_key: T.nilable(::String), category: T.nilable(::String), message: T.nilable(::String), metadata: T.nilable(Models::Shared::PartnerManagedCompanyMigrationReadinessResponseMetadata)).void }
        def initialize(error_key: nil, category: nil, message: nil, metadata: nil)
          @error_key = error_key
          @category = category
          @message = message
          @metadata = metadata
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @error_key == other.error_key
          return false unless @category == other.category
          return false unless @message == other.message
          return false unless @metadata == other.metadata
          true
        end
      end
    end
  end
end
