# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared

      class ExternalPayrollUpdateRequestEarnings
        extend T::Sig
        include Crystalline::MetadataFields

        # The earning type class name.
        field :earning_type, Crystalline::Nilable.new(Models::Shared::ExternalPayrollUpdateRequestEarningType), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('earning_type'), 'decoder': ::GustoEmbedded::Utils.enum_from_string(Models::Shared::ExternalPayrollUpdateRequestEarningType, true) } }
        # The ID of the earning type.
        field :earning_id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('earning_id') } }
        # The earning amount in dollars.
        field :amount, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('amount') } }
        # The number of hours worked.
        field :hours, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('hours') } }

        sig { params(earning_type: T.nilable(Models::Shared::ExternalPayrollUpdateRequestEarningType), earning_id: T.nilable(::Integer), amount: T.nilable(::String), hours: T.nilable(::String)).void }
        def initialize(earning_type: nil, earning_id: nil, amount: nil, hours: nil)
          @earning_type = earning_type
          @earning_id = earning_id
          @amount = amount
          @hours = hours
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @earning_type == other.earning_type
          return false unless @earning_id == other.earning_id
          return false unless @amount == other.amount
          return false unless @hours == other.hours
          true
        end
      end
    end
  end
end
