# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
      # Request body for creating an employee's I-9 authorization verification documents.
      class I9AuthorizationDocumentsRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # An array of I-9 verification documents. Every request must contain the complete list of documents for the employee, as previous records are replaced.
        field :documents, Crystalline::Array.new(Models::Shared::Documents), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('documents'), required: true } }

        sig { params(documents: T::Array[Models::Shared::Documents]).void }
        def initialize(documents:)
          @documents = documents
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @documents == other.documents
          true
        end
      end
    end
  end
end
