# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared

      class LiabilitySelections
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the tax.
        field :tax_id, ::Integer, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('tax_id'), required: true } }
        # The total cumulative unpaid liability amount for this tax across all external payrolls up to and including the one specified by `last_unpaid_external_payroll_uuid`.
        field :unpaid_liability_amount, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('unpaid_liability_amount'), required: true } }
        # The UUID of the last external payroll with an unpaid liability for this tax. Set to `null` to indicate no liability.
        field :last_unpaid_external_payroll_uuid, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('last_unpaid_external_payroll_uuid'), required: true } }

        sig { params(tax_id: ::Integer, unpaid_liability_amount: ::String, last_unpaid_external_payroll_uuid: T.nilable(::String)).void }
        def initialize(tax_id:, unpaid_liability_amount:, last_unpaid_external_payroll_uuid: nil)
          @tax_id = tax_id
          @unpaid_liability_amount = unpaid_liability_amount
          @last_unpaid_external_payroll_uuid = last_unpaid_external_payroll_uuid
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @tax_id == other.tax_id
          return false unless @unpaid_liability_amount == other.unpaid_liability_amount
          return false unless @last_unpaid_external_payroll_uuid == other.last_unpaid_external_payroll_uuid
          true
        end
      end
    end
  end
end
