# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  
    # NotificationStatus - Represents the notification's status as managed by our system. It is updated based on observable system events and internal business logic, and does not reflect resolution steps taken outside our system. This field is read-only and cannot be modified via the API.
    class NotificationStatus < T::Enum
      enums do
        OPEN = new('open')
        RESOLVED = new('resolved')
        EXPIRED = new('expired')
      end
    end
  end
end
