# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared

      class Occupations
        extend T::Sig
        include Crystalline::MetadataFields

        # Bureau of Labor Statistics (BLS) occupation code.
        field :code, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('code'), required: true } }
        # Experience level for this occupation.
        field :experience_level, Models::Shared::ExperienceLevel, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('experience_level'), required: true, 'decoder': ::GustoEmbedded::Utils.enum_from_string(Models::Shared::ExperienceLevel, false) } }
        # Percentage of time spent in this occupation (as decimal string, 0-1).
        field :time_percentage, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('time_percentage'), required: true } }
        # Occupation name.
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('name') } }
        # Occupation description.
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('description') } }
        # Whether this is the primary occupation.
        field :primary, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('primary') } }

        sig { params(code: ::String, experience_level: Models::Shared::ExperienceLevel, time_percentage: ::String, name: T.nilable(::String), description: T.nilable(::String), primary: T.nilable(T::Boolean)).void }
        def initialize(code:, experience_level:, time_percentage:, name: nil, description: nil, primary: nil)
          @code = code
          @experience_level = experience_level
          @time_percentage = time_percentage
          @name = name
          @description = description
          @primary = primary
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @code == other.code
          return false unless @experience_level == other.experience_level
          return false unless @time_percentage == other.time_percentage
          return false unless @name == other.name
          return false unless @description == other.description
          return false unless @primary == other.primary
          true
        end
      end
    end
  end
end
