# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
    
      # An array of hourly compensations for the employee. Hourly compensations include regular, overtime, and double overtime hours.
      class PayrollUpdateHourlyCompensations
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the compensation. This also serves as the unique, immutable identifier for this compensation.
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('name') } }
        # The number of hours to be compensated for this pay period.
        field :hours, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('hours') } }
        # The UUIDs of the job for the compensation.
        field :job_uuid, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('job_uuid') } }

        sig { params(name: T.nilable(::String), hours: T.nilable(::String), job_uuid: T.nilable(::String)).void }
        def initialize(name: nil, hours: nil, job_uuid: nil)
          @name = name
          @hours = hours
          @job_uuid = job_uuid
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name == other.name
          return false unless @hours == other.hours
          return false unless @job_uuid == other.job_uuid
          true
        end
      end
    end
  end
end
