# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
    

      class PayrollUpdatePaidTimeOff
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the PTO. This also serves as the unique, immutable identifier for the PTO. Must pass in name or policy_uuid but not both.
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('name') } }
        # The hours of this PTO taken during the pay period.
        field :hours, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('hours') } }
        # The uuid of the PTO policy. Must pass in name or policy_uuid but not both.
        field :policy_uuid, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('policy_uuid') } }
        # The outstanding hours paid upon termination. This field is only applicable for termination payrolls.
        field :final_payout_unused_hours_input, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('final_payout_unused_hours_input') } }

        sig { params(name: T.nilable(::String), hours: T.nilable(::String), policy_uuid: T.nilable(::String), final_payout_unused_hours_input: T.nilable(::String)).void }
        def initialize(name: nil, hours: nil, policy_uuid: nil, final_payout_unused_hours_input: nil)
          @name = name
          @hours = hours
          @policy_uuid = policy_uuid
          @final_payout_unused_hours_input = final_payout_unused_hours_input
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name == other.name
          return false unless @hours == other.hours
          return false unless @policy_uuid == other.policy_uuid
          return false unless @final_payout_unused_hours_input == other.final_payout_unused_hours_input
          true
        end
      end
    end
  end
end
