# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  
    # PayrollPartnerDisbursementsPaymentMethod - The payment method for the disbursement
    class PayrollPartnerDisbursementsPaymentMethod < T::Enum
      enums do
        DIRECT_DEPOSIT = new('Direct Deposit')
        CHECK = new('Check')
      end
    end
  end
end
