# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  
    # PayrollPartnerDisbursementsPaymentStatus - The status of the payment
    class PayrollPartnerDisbursementsPaymentStatus < T::Enum
      enums do
        PENDING = new('Pending')
        PAID = new('Paid')
        NOT_PARTNER_MANAGED = new('Not partner managed')
        CONVERTED_TO_CHECK = new('Converted to check')
      end
    end
  end
end
