# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared

      class RecurringReimbursement
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of this recurring reimbursement.
        field :uuid, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('uuid'), required: true } }
        # The UUID of the employee.
        field :employee_uuid, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('employee_uuid'), required: true } }
        # The description of the reimbursement.
        field :description, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('description'), required: true } }
        # The dollar amount of the reimbursement.
        field :amount, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('amount'), required: true } }
        # The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
        field :version, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('version'), required: true } }
        # The timestamp when this reimbursement was created.
        field :created_at, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('created_at') } }
        # The timestamp when this reimbursement was last updated.
        field :updated_at, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('updated_at') } }

        sig { params(uuid: ::String, employee_uuid: ::String, description: ::String, amount: ::String, version: ::String, created_at: T.nilable(::String), updated_at: T.nilable(::String)).void }
        def initialize(uuid:, employee_uuid:, description:, amount:, version:, created_at: nil, updated_at: nil)
          @uuid = uuid
          @employee_uuid = employee_uuid
          @description = description
          @amount = amount
          @version = version
          @created_at = created_at
          @updated_at = updated_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @uuid == other.uuid
          return false unless @employee_uuid == other.employee_uuid
          return false unless @description == other.description
          return false unless @amount == other.amount
          return false unless @version == other.version
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          true
        end
      end
    end
  end
end
