# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
    

      class States
        extend T::Sig
        include Crystalline::MetadataFields


        field :state, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('state'), required: true } }

        field :questions, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::Questions)), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('questions') } }

        sig { params(state: ::String, questions: T.nilable(T::Array[Models::Shared::Questions])).void }
        def initialize(state:, questions: nil)
          @state = state
          @questions = questions
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @state == other.state
          return false unless @questions == other.questions
          true
        end
      end
    end
  end
end
