# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  

    class VersionHeader < T::Enum
      enums do
        TWO_THOUSAND_AND_TWENTY_FIVE_06_15 = new('2025-06-15')
      end
    end
  end
end
