# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations

      class Batch
        extend T::Sig
        include Crystalline::MetadataFields

        # The type of entity to act on.
        field(
          :entity_type,
          Models::Operations::EntityType,
          {
            'format_json': {
              'letter_case': ::GustoEmbedded::Utils.field_name("entity_type"),
              required: true,
              'decoder': ::GustoEmbedded::Utils.enum_from_string(Models::Operations::EntityType, false)
            }
          }
        )
        # The UUID of the payroll to cancel. Payrolls the partner is not authorized to access, or that do not exist, appear in the response's `exclusions` array.
        field(
          :uuid,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("uuid"), required: true}}
        )
        # The UUID of the company that owns the payroll. The partner must be mapped to this company.
        field(
          :company_uuid,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("company_uuid"), required: true}}
        )

        sig { params(entity_type: Models::Operations::EntityType, uuid: ::String, company_uuid: ::String).void }
        def initialize(entity_type:, uuid:, company_uuid:)
          @entity_type = entity_type
          @uuid = uuid
          @company_uuid = company_uuid
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @entity_type == other.entity_type
          return false unless @uuid == other.uuid
          return false unless @company_uuid == other.company_uuid
          true
        end
      end
    end
  end
end
