# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations
      # Department details for the employee
      class Department
        extend T::Sig
        include Crystalline::MetadataFields

        # UUID of an existing company department
        field(
          :department_uuid,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("department_uuid"), required: true}}
        )

        sig { params(department_uuid: ::String).void }
        def initialize(department_uuid:)
          @department_uuid = department_uuid
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @department_uuid == other.department_uuid
          true
        end
      end
    end
  end
end
