# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations
      # EntityType - The type of entity to create
      class EntityType < T::Enum
        enums do
          EMPLOYEE = new("employee")
        end
      end
    end
  end
end
