# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations

      class GetV1CompaniesCompanyIdContractorPaymentsResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # A JSON object containing contractor payments information
        field(
          :one_of,
          Crystalline::Nilable.new(
            Crystalline::Union.new(
              Models::Shared::ContractorPaymentSummary,
              Models::Shared::ContractorPaymentSummaryByDates
            )
          )
        )

        sig {
          params(
            content_type: ::String,
            status_code: ::Integer,
            raw_response: ::Faraday::Response,
            one_of: T.nilable(
              T.any(Models::Shared::ContractorPaymentSummary, Models::Shared::ContractorPaymentSummaryByDates)
            )
          )
            .void
        }
        def initialize(content_type:, status_code:, raw_response:, one_of: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @one_of = one_of
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @one_of == other.one_of
          true
        end
      end
    end
  end
end
