# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations
      # GetV1CompaniesCompanyUuidTimeOffRequestsHeaderXGustoAPIVersion - Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
      class GetV1CompaniesCompanyUuidTimeOffRequestsHeaderXGustoAPIVersion < T::Enum
        enums do
          TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_11_MINUS_15 = new("2025-11-15")
        end
      end
    end
  end
end
