# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations

      class GetAchTransactionsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The UUID of the company
        field(
          :company_uuid,
          ::String,
          {'path_param': {'field_name': "company_uuid", 'style': "simple", 'explode': false}}
        )
        # The UUID of the contractor payment
        field(
          :contractor_payment_uuid,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "contractor_payment_uuid", 'style': "form", 'explode': true}}
        )
        # The UUID of the payroll
        field(
          :payroll_uuid,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "payroll_uuid", 'style': "form", 'explode': true}}
        )
        # Used to filter the ACH transactions to only include those with a specific transaction type, such as "Credit employee pay".
        field(
          :transaction_type,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "transaction_type", 'style': "form", 'explode': true}}
        )
        # Used to filter the ACH transactions to only include those with a specific payment direction, either "credit" or "debit".
        field(
          :payment_direction,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "payment_direction", 'style': "form", 'explode': true}}
        )
        # The page that is requested. When unspecified, will load all objects unless endpoint forces pagination.
        field(
          :page,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page", 'style': "form", 'explode': true}}
        )
        # Number of objects per page. For majority of endpoints will default to 25
        field(
          :per,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "per", 'style': "form", 'explode': true}}
        )
        # Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
        field(
          :x_gusto_api_version,
          Crystalline::Nilable.new(Models::Operations::GetAchTransactionsHeaderXGustoAPIVersion),
          {'header': {'field_name': "X-Gusto-API-Version", 'style': "simple", 'explode': false}}
        )

        sig {
          params(
            company_uuid: ::String,
            contractor_payment_uuid: T.nilable(::String),
            payroll_uuid: T.nilable(::String),
            transaction_type: T.nilable(::String),
            payment_direction: T.nilable(::String),
            page: T.nilable(::Integer),
            per: T.nilable(::Integer),
            x_gusto_api_version: T.nilable(Models::Operations::GetAchTransactionsHeaderXGustoAPIVersion)
          )
            .void
        }
        def initialize(
          company_uuid:,
          contractor_payment_uuid: nil,
          payroll_uuid: nil,
          transaction_type: nil,
          payment_direction: nil,
          page: nil,
          per: nil,
          x_gusto_api_version: Models::Operations::GetAchTransactionsHeaderXGustoAPIVersion::TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_11_MINUS_15
        )
          @company_uuid = company_uuid
          @contractor_payment_uuid = contractor_payment_uuid
          @payroll_uuid = payroll_uuid
          @transaction_type = transaction_type
          @payment_direction = payment_direction
          @page = page
          @per = per
          @x_gusto_api_version = x_gusto_api_version
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @company_uuid == other.company_uuid
          return false unless @contractor_payment_uuid == other.contractor_payment_uuid
          return false unless @payroll_uuid == other.payroll_uuid
          return false unless @transaction_type == other.transaction_type
          return false unless @payment_direction == other.payment_direction
          return false unless @page == other.page
          return false unless @per == other.per
          return false unless @x_gusto_api_version == other.x_gusto_api_version
          true
        end
      end
    end
  end
end
