# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations

      class Person
        extend T::Sig
        include Crystalline::MetadataFields

        # External identifier for the person
        field(
          :external_id,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("external_id"), required: true}}
        )
        # Legal first name
        field(
          :first_name,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("first_name"), required: true}}
        )
        # Legal last name
        field(
          :last_name,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("last_name"), required: true}}
        )
        # Middle initial
        field(
          :middle_initial,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("middle_initial")}}
        )
        # Preferred first name
        field(
          :preferred_first_name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("preferred_first_name")}}
        )
        # Personal email address
        field(
          :email,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("email")}}
        )
        # Work email address
        field(
          :work_email,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("work_email")}}
        )
        # Social Security Number (format: xxx-xx-xxxx)
        field(
          :ssn,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("ssn")}}
        )
        # Date of birth (YYYY-MM-DD)
        field(
          :date_of_birth,
          Crystalline::Nilable.new(::Date),
          {
            'format_json': {
              'letter_case': ::GustoEmbedded::Utils.field_name("date_of_birth"),
              'decoder': ::GustoEmbedded::Utils.date_from_iso_format(true)
            }
          }
        )
        # Whether the employee will complete their own onboarding
        field(
          :self_onboarding,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("self_onboarding")}}
        )

        sig {
          params(
            external_id: ::String,
            first_name: ::String,
            last_name: ::String,
            middle_initial: T.nilable(::String),
            preferred_first_name: T.nilable(::String),
            email: T.nilable(::String),
            work_email: T.nilable(::String),
            ssn: T.nilable(::String),
            date_of_birth: T.nilable(::Date),
            self_onboarding: T.nilable(T::Boolean)
          )
            .void
        }
        def initialize(
          external_id:,
          first_name:,
          last_name:,
          middle_initial: nil,
          preferred_first_name: nil,
          email: nil,
          work_email: nil,
          ssn: nil,
          date_of_birth: nil,
          self_onboarding: nil
        )
          @external_id = external_id
          @first_name = first_name
          @last_name = last_name
          @middle_initial = middle_initial
          @preferred_first_name = preferred_first_name
          @email = email
          @work_email = work_email
          @ssn = ssn
          @date_of_birth = date_of_birth
          @self_onboarding = self_onboarding
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @external_id == other.external_id
          return false unless @first_name == other.first_name
          return false unless @last_name == other.last_name
          return false unless @middle_initial == other.middle_initial
          return false unless @preferred_first_name == other.preferred_first_name
          return false unless @email == other.email
          return false unless @work_email == other.work_email
          return false unless @ssn == other.ssn
          return false unless @date_of_birth == other.date_of_birth
          return false unless @self_onboarding == other.self_onboarding
          true
        end
      end
    end
  end
end
