# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations
      # PolicyType - Type of the time off policy. Currently only "vacation" and "sick" are supported
      class PolicyType < T::Enum
        enums do
          VACATION = new("vacation")
          SICK = new("sick")
        end
      end
    end
  end
end
