# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations

      class PostV1EmployeesEmployeeIdRecurringReimbursementsRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The description of the reimbursement
        field(
          :description,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("description"), required: true}}
        )
        # The dollar amount of the reimbursement
        field(
          :amount,
          ::Float,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("amount"), required: true}}
        )

        sig { params(description: ::String, amount: ::Float).void }
        def initialize(description:, amount:)
          @description = description
          @amount = amount
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @description == other.description
          return false unless @amount == other.amount
          true
        end
      end
    end
  end
end
