# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations

      class PutV1EmployeesEmployeeIdFederalTaxesRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/versioning#object-layer) for information on how to use this field.
        field(
          :version,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("version"), required: true}}
        )
        # The version of the W4 form. Only rev_2020_w4 is accepted for updates.
        field(
          :w4_data_type,
          Models::Operations::W4DataType,
          {
            'format_json': {
              'letter_case': ::GustoEmbedded::Utils.field_name("w4_data_type"),
              required: true,
              'decoder': ::GustoEmbedded::Utils.enum_from_string(Models::Operations::W4DataType, false)
            }
          }
        )
        # Determines which tax return form an individual will use. One of: Single, Married, Head of Household, Exempt from withholding.
        field(
          :filing_status,
          Models::Operations::FilingStatus,
          {
            'format_json': {
              'letter_case': ::GustoEmbedded::Utils.field_name("filing_status"),
              required: true,
              'decoder': ::GustoEmbedded::Utils.enum_from_string(Models::Operations::FilingStatus, false)
            }
          }
        )
        # If there are only two jobs (e.g., you and your spouse each have a job), set to true.
        field(
          :two_jobs,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("two_jobs")}}
        )
        # Amount for dependents; a dependent entitles the taxpayer to claim a dependency exemption.
        field(
          :dependents_amount,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("dependents_amount")}}
        )
        # Other income amount.
        field(
          :other_income,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("other_income")}}
        )
        # Deductions other than the standard deduction to reduce withholding.
        field(
          :deductions,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("deductions")}}
        )
        # Additional amount to be withheld from each paycheck.
        field(
          :extra_withholding,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("extra_withholding")}}
        )
        # Only applicable when w4_data_type is 'pre_2020_w4' (pre-2020 W4 forms are deprecated for updates).
        field(
          :federal_withholding_allowance,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("federal_withholding_allowance")}}
        )
        # Only applicable when w4_data_type is 'pre_2020_w4' (pre-2020 W4 forms are deprecated for updates).
        field(
          :additional_withholding,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("additional_withholding")}}
        )

        sig {
          params(
            version: ::String,
            w4_data_type: Models::Operations::W4DataType,
            filing_status: Models::Operations::FilingStatus,
            two_jobs: T.nilable(T::Boolean),
            dependents_amount: T.nilable(::Float),
            other_income: T.nilable(::Float),
            deductions: T.nilable(::Float),
            extra_withholding: T.nilable(::Float),
            federal_withholding_allowance: T.nilable(::Integer),
            additional_withholding: T.nilable(::Float)
          )
            .void
        }
        def initialize(
          version:,
          w4_data_type:,
          filing_status:,
          two_jobs: nil,
          dependents_amount: nil,
          other_income: nil,
          deductions: nil,
          extra_withholding: nil,
          federal_withholding_allowance: nil,
          additional_withholding: nil
        )
          @version = version
          @w4_data_type = w4_data_type
          @filing_status = filing_status
          @two_jobs = two_jobs
          @dependents_amount = dependents_amount
          @other_income = other_income
          @deductions = deductions
          @extra_withholding = extra_withholding
          @federal_withholding_allowance = federal_withholding_allowance
          @additional_withholding = additional_withholding
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @version == other.version
          return false unless @w4_data_type == other.w4_data_type
          return false unless @filing_status == other.filing_status
          return false unless @two_jobs == other.two_jobs
          return false unless @dependents_amount == other.dependents_amount
          return false unless @other_income == other.other_income
          return false unless @deductions == other.deductions
          return false unless @extra_withholding == other.extra_withholding
          return false unless @federal_withholding_allowance == other.federal_withholding_allowance
          return false unless @additional_withholding == other.additional_withholding
          true
        end
      end
    end
  end
end
