# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations

      class PutV1ContractorDocumentSignRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The UUID of the document
        field(
          :document_uuid,
          ::String,
          {'path_param': {'field_name': "document_uuid", 'style': "simple", 'explode': false}}
        )

        field(
          :body,
          Models::Operations::PutV1ContractorDocumentSignRequestBody,
          {'request': {'media_type': "application/json"}}
        )
        # Optional header to supply the IP address. This can be used to supply the IP address for signature endpoints instead of the signed_by_ip_address parameter.
        field(
          :x_gusto_client_ip,
          Crystalline::Nilable.new(::String),
          {'header': {'field_name': "x-gusto-client-ip", 'style': "simple", 'explode': false}}
        )
        # Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
        field(
          :x_gusto_api_version,
          Crystalline::Nilable.new(Models::Operations::PutV1ContractorDocumentSignHeaderXGustoAPIVersion),
          {'header': {'field_name': "X-Gusto-API-Version", 'style': "simple", 'explode': false}}
        )

        sig {
          params(
            document_uuid: ::String,
            body: Models::Operations::PutV1ContractorDocumentSignRequestBody,
            x_gusto_client_ip: T.nilable(::String),
            x_gusto_api_version: T.nilable(Models::Operations::PutV1ContractorDocumentSignHeaderXGustoAPIVersion)
          )
            .void
        }
        def initialize(
          document_uuid:,
          body:,
          x_gusto_client_ip: nil,
          x_gusto_api_version: Models::Operations::PutV1ContractorDocumentSignHeaderXGustoAPIVersion::TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_11_MINUS_15
        )
          @document_uuid = document_uuid
          @body = body
          @x_gusto_client_ip = x_gusto_client_ip
          @x_gusto_api_version = x_gusto_api_version
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @document_uuid == other.document_uuid
          return false unless @body == other.body
          return false unless @x_gusto_client_ip == other.x_gusto_client_ip
          return false unless @x_gusto_api_version == other.x_gusto_api_version
          true
        end
      end
    end
  end
end
