# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations
      # QueryParamSortBy - Sort employee compensations by name
      class QueryParamSortBy < T::Enum
        enums do
          FIRST_NAME = new("first_name")
          LAST_NAME = new("last_name")
        end
      end
    end
  end
end
