# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Operations

      class SubmitInformationRequestRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :required_questions,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Operations::RequiredQuestions)),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("required_questions")}}
        )

        sig { params(required_questions: T.nilable(T::Array[Models::Operations::RequiredQuestions])).void }
        def initialize(required_questions: nil)
          @required_questions = required_questions
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @required_questions == other.required_questions
          true
        end
      end
    end
  end
end
