# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  

    class BenefitTypeRequirementsDeductAsPercentageDefaultValue < ::Crystalline::FieldAugmented
      extend T::Sig


      field :type, T.nilable(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('type') } }

      field :value, T.nilable(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('value') } }


      sig { params(type: T.nilable(::String), value: T.nilable(::String)).void }
      def initialize(type: nil, value: nil)
        @type = type
        @value = value
      end
    end
  end
end
