# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Shared
  
    # The representation of an contractor's onboarding status.
    class ContractorOnboardingStatus < ::Crystalline::FieldAugmented
      extend T::Sig

      # Unique identifier for this contractor.
      field :uuid, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('uuid') } }
      # One of the "onboarding_status" enum values.
      field :onboarding_status, T.nilable(::GustoEmbedded::Shared::ContractorOnboardingStatusOnboardingStatus), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('onboarding_status'), 'decoder': Utils.enum_from_string(::GustoEmbedded::Shared::ContractorOnboardingStatusOnboardingStatus, true) } }
      # List of steps required to onboard a contractor.
      field :onboarding_steps, T.nilable(T::Array[::GustoEmbedded::Shared::ContractorOnboardingStatusOnboardingStep]), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('onboarding_steps') } }


      sig { params(uuid: ::String, onboarding_status: T.nilable(::GustoEmbedded::Shared::ContractorOnboardingStatusOnboardingStatus), onboarding_steps: T.nilable(T::Array[::GustoEmbedded::Shared::ContractorOnboardingStatusOnboardingStep])).void }
      def initialize(uuid: nil, onboarding_status: nil, onboarding_steps: nil)
        @uuid = uuid
        @onboarding_status = onboarding_status
        @onboarding_steps = onboarding_steps
      end
    end
  end
end
