# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Errors
      autoload :APIError, 'gusto_embedded/models/errors/apierror.rb'
      autoload :CompanySuspensionCreationErrors, 'gusto_embedded/models/errors/company_suspension_creation_errors.rb'
      autoload :NotFoundErrorObject, 'gusto_embedded/models/errors/not_found_error_object.rb'
      autoload :UnprocessableEntityErrorObject, 'gusto_embedded/models/errors/unprocessable_entity_error_object.rb'
      autoload :Base, 'gusto_embedded/models/errors/base.rb'
      autoload :CheckDate, 'gusto_embedded/models/errors/check_date.rb'
      autoload :DeleteV1CompanyBenefitsCompanyBenefitIdResponseBody, 'gusto_embedded/models/errors/delete_v1_company_benefits_company_benefit_id_responsebody.rb'
      autoload :Errors, 'gusto_embedded/models/errors/errors.rb'
      autoload :GetCompaniesCompanyUuidContractorPaymentsPreviewBase, 'gusto_embedded/models/errors/get_companies_company_uuid_contractor_payments_preview_base.rb'
      autoload :GetCompaniesCompanyUuidContractorPaymentsPreviewErrors, 'gusto_embedded/models/errors/get_companies_company_uuid_contractor_payments_preview_errors.rb'
      autoload :GetCompaniesCompanyUuidContractorPaymentsPreviewResponseBody, 'gusto_embedded/models/errors/get_companies_company_uuid_contractor_payments_preview_responsebody.rb'
    end
  end
end
