# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetV1CompaniesCompanyIdPayrollsPayrollIdRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The UUID of the company
      field :company_id, ::String, { 'path_param': { 'field_name': 'company_id', 'style': 'simple', 'explode': false } }
      # The UUID of the payroll
      field :payroll_id, ::String, { 'path_param': { 'field_name': 'payroll_id', 'style': 'simple', 'explode': false } }
      # Include the requested attribute in the response, for multiple attributes comma separate the values, i.e. `?include=benefits,deductions,taxes`
      field :include, T.nilable(T::Array[::OpenApiSDK::Operations::GetV1CompaniesCompanyIdPayrollsPayrollIdQueryParamInclude]), { 'query_param': { 'field_name': 'include', 'style': 'form', 'explode': false } }
      # Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
      field :x_gusto_api_version, T.nilable(::OpenApiSDK::Shared::VersionHeader), { 'header': { 'field_name': 'X-Gusto-API-Version', 'style': 'simple', 'explode': false } }


      sig { params(company_id: ::String, payroll_id: ::String, include: T.nilable(T::Array[::OpenApiSDK::Operations::GetV1CompaniesCompanyIdPayrollsPayrollIdQueryParamInclude]), x_gusto_api_version: T.nilable(::OpenApiSDK::Shared::VersionHeader)).void }
      def initialize(company_id: nil, payroll_id: nil, include: nil, x_gusto_api_version: nil)
        @company_id = company_id
        @payroll_id = payroll_id
        @include = include
        @x_gusto_api_version = x_gusto_api_version
      end
    end
  end
end
