# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class PutV1EmployeesEmployeeIdStateTaxesRequestBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :states, T::Array[::OpenApiSDK::Operations::States], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('states') } }


      sig { params(states: T::Array[::OpenApiSDK::Operations::States]).void }
      def initialize(states: nil)
        @states = states
      end
    end
  end
end
