# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class PutV1EmployeesEmployeeIdOnboardingStatusRequestBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The updated onboarding status for the employee
      field :onboarding_status, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('onboarding_status') } }


      sig { params(onboarding_status: ::String).void }
      def initialize(onboarding_status: nil)
        @onboarding_status = onboarding_status
      end
    end
  end
end
