# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Operations

      class GetV1CompaniesCompanyIdLocationsResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # Success
        field :company_locations_list, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::Location))

        sig { params(content_type: ::String, status_code: ::Integer, raw_response: ::Faraday::Response, company_locations_list: T.nilable(T::Array[Models::Shared::Location])).void }
        def initialize(content_type:, status_code:, raw_response:, company_locations_list: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @company_locations_list = company_locations_list
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @company_locations_list == other.company_locations_list
          true
        end
      end
    end
  end
end
