# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Operations

      class PostV1PlaidProcessorTokenRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :plaid_processor_token_request, Models::Shared::PlaidProcessorTokenRequest, { 'request': { 'media_type': 'application/json' } }
        # Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
        field :x_gusto_api_version, Crystalline::Nilable.new(Models::Operations::PostV1PlaidProcessorTokenHeaderXGustoAPIVersion), { 'header': { 'field_name': 'X-Gusto-API-Version', 'style': 'simple', 'explode': false } }

        sig { params(plaid_processor_token_request: Models::Shared::PlaidProcessorTokenRequest, x_gusto_api_version: T.nilable(Models::Operations::PostV1PlaidProcessorTokenHeaderXGustoAPIVersion)).void }
        def initialize(plaid_processor_token_request:, x_gusto_api_version: Models::Operations::PostV1PlaidProcessorTokenHeaderXGustoAPIVersion::TWO_THOUSAND_AND_TWENTY_SIX_MINUS_06_MINUS_15)
          @plaid_processor_token_request = plaid_processor_token_request
          @x_gusto_api_version = x_gusto_api_version
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @plaid_processor_token_request == other.plaid_processor_token_request
          return false unless @x_gusto_api_version == other.x_gusto_api_version
          true
        end
      end
    end
  end
end
