workflowVersion: 1.0.0
speakeasyVersion: 1.513.4
sources:
    GustoEmbedded-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/Gusto/Gusto-Partner-API/refs/heads/ar/poc-new-field-staging-deploy/generated/embedded/api.v2024-04-01.embedded.yaml
              authHeader: Authorization
              authSecret: $openapi_doc_auth_token
        overlays:
            - location: https://raw.githubusercontent.com/Gusto/Gusto-Partner-API/refs/heads/ar/poc-new-field-staging-deploy/.speakeasy/speakeasy-modifications-overlay.yaml
              authHeader: Authorization
              authSecret: $openapi_doc_auth_token
        registry:
            location: registry.speakeasyapi.dev/gusto/ruby-sdk/gusto-embedded-oas
targets:
    gusto-embedded:
        target: ruby
        source: GustoEmbedded-OAS
        output: ./gusto_embedded
        publish:
            rubygems:
                token: $rubygems_auth_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gusto/ruby-sdk/gusto-embedded-oas-code-samples
            labelOverride:
                fixedValue: Ruby (SDK)
            blocking: false
