# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class VersionHeader < T::Enum
      enums do
        TWO_THOUSAND_AND_TWENTY_FOUR_04_01 = new('2024-04-01')
      end
    end
  end
end
