# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Errors
      # Error response when a payroll digest idempotency key has already been used by the same partner.
      class PayrollDigestConflictError < StandardError
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :errors,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Errors::PayrollDigestConflictErrorErrors)),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("errors")}}
        )

        sig { params(errors: T.nilable(T::Array[Models::Errors::PayrollDigestConflictErrorErrors])).void }
        def initialize(errors: nil)
          @errors = errors
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @errors == other.errors
          true
        end
      end
    end
  end
end
