# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
      # Request body for creating an employee's Section 603 high earner status
      class EmployeeSection603HighEarnerStatusCreateRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The year for which this high earner status applies
        field :effective_year, ::Integer, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('effective_year'), required: true } }
        # Whether the employee is classified as a high earner for Section 603 purposes
        field :is_high_earner, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('is_high_earner'), required: true } }

        sig { params(effective_year: ::Integer, is_high_earner: T::Boolean).void }
        def initialize(effective_year:, is_high_earner:)
          @effective_year = effective_year
          @is_high_earner = is_high_earner
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @effective_year == other.effective_year
          return false unless @is_high_earner == other.is_high_earner
          true
        end
      end
    end
  end
end
