# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
      # Configuration for which onboarding documents (e.g. Form I-9) are required for an employee during onboarding.
      class EmployeeOnboardingDocument
        extend T::Sig
        include Crystalline::MetadataFields

        # Whether to include Form I-9 for this employee during onboarding.
        # When true, the employee will be prompted to complete Form I-9 as part of their onboarding.
        #
        field :i9_document, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('i9_document') } }
        # The UUID of the onboarding documents config record. Null when no config has been saved yet.
        field :uuid, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('uuid') } }

        sig { params(i9_document: T.nilable(T::Boolean), uuid: T.nilable(::String)).void }
        def initialize(i9_document: nil, uuid: nil)
          @i9_document = i9_document
          @uuid = uuid
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @i9_document == other.i9_document
          return false unless @uuid == other.uuid
          true
        end
      end
    end
  end
end
