# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared

      class IdentityVerificationStatus < T::Enum
        enums do
          PASS = new('Pass')
          FAIL = new('Fail')
          SKIPPED = new('Skipped')
        end
      end
    end
  end
end
