# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
      # single entity
      class MetadataWithOneEntity
        extend T::Sig
        include Crystalline::MetadataFields

        # Name of the entity that the error corresponds to.
        field :entity_type, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('entity_type') } }
        # Unique identifier for the entity.
        field :entity_uuid, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('entity_uuid') } }

        field :additional_properties, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('additional_properties'), 'additional_properties': true } }

        field :valid_from, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('valid_from') } }

        field :valid_up_to, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('valid_up_to') } }

        field :key, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('key') } }

        field :state, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('state') } }

        sig { params(entity_type: T.nilable(::String), entity_uuid: T.nilable(::String), additional_properties: T.nilable(T::Hash[Symbol, ::Object]), valid_from: T.nilable(::String), valid_up_to: T.nilable(::String), key: T.nilable(::String), state: T.nilable(::String)).void }
        def initialize(entity_type: nil, entity_uuid: nil, additional_properties: nil, valid_from: nil, valid_up_to: nil, key: nil, state: nil)
          @entity_type = entity_type
          @entity_uuid = entity_uuid
          @additional_properties = additional_properties
          @valid_from = valid_from
          @valid_up_to = valid_up_to
          @key = key
          @state = state
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @entity_type == other.entity_type
          return false unless @entity_uuid == other.entity_uuid
          return false unless @additional_properties == other.additional_properties
          return false unless @valid_from == other.valid_from
          return false unless @valid_up_to == other.valid_up_to
          return false unless @key == other.key
          return false unless @state == other.state
          true
        end
      end
    end
  end
end
