# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
      # Preview of pay schedule dates for the next 18 months. Use this to show partners expected pay dates, pay period boundaries, and payroll deadlines before they create or change a pay schedule. See [Preview pay schedule dates](https://docs.gusto.com/embedded-payroll/reference/get-v1-companies-company_id-pay_schedules-preview) for usage.
      #
      # - **pay_periods**: One entry per pay period in the range; each includes check_date, start_date, end_date, and run_payroll_by.
      # - **holidays**: Observed bank holidays (ISO date strings) that may affect payroll timing.
      #
      class PaySchedulePreview
        extend T::Sig
        include Crystalline::MetadataFields

        # A list of pay periods for the previewed pay schedule (default range is 18 months from today, or up to end_date when provided).
        field :pay_periods, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::PaySchedulePreviewPayPeriod)), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('pay_periods') } }
        # A list of dates for bank closures (ISO date strings); may affect payroll processing.
        field :holidays, Crystalline::Nilable.new(Crystalline::Array.new(::Date)), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('holidays') } }

        sig { params(pay_periods: T.nilable(T::Array[Models::Shared::PaySchedulePreviewPayPeriod]), holidays: T.nilable(T::Array[::Date])).void }
        def initialize(pay_periods: nil, holidays: nil)
          @pay_periods = pay_periods
          @holidays = holidays
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @pay_periods == other.pay_periods
          return false unless @holidays == other.holidays
          true
        end
      end
    end
  end
end
