# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
      # PaymentSpeed - Payment speed. READ-ONLY.
      # - `1-day`: Next-day ACH (only for partners that opt in).
      # - `2-day`: Two-day ACH.
      # - `4-day`: Standard ACH.
      #
      class PaymentSpeed < T::Enum
        enums do
          ONE_MINUS_DAY = new('1-day')
          TWO_MINUS_DAY = new('2-day')
          FOUR_MINUS_DAY = new('4-day')
        end
      end
    end
  end
end
