# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
      # Request body for calculating gross up amount
      class PayrollGrossUpRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The UUID of the employee
        field :employee_uuid, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('employee_uuid'), required: true } }
        # Employee net earnings
        field :net_pay, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('net_pay'), required: true } }

        sig { params(employee_uuid: ::String, net_pay: ::String).void }
        def initialize(employee_uuid:, net_pay:)
          @employee_uuid = employee_uuid
          @net_pay = net_pay
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @employee_uuid == other.employee_uuid
          return false unless @net_pay == other.net_pay
          true
        end
      end
    end
  end
end
