# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared

      class Report
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier of the report request
        field :request_uuid, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('request_uuid') } }
        # Current status of the report, possible values are 'succeeded', 'pending', or 'failed'
        field :status, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('status') } }
        # The array of urls to access the report
        field :report_urls, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('report_urls') } }

        sig { params(request_uuid: T.nilable(::String), status: T.nilable(::String), report_urls: T.nilable(T::Array[::String])).void }
        def initialize(request_uuid: nil, status: nil, report_urls: nil)
          @request_uuid = request_uuid
          @status = status
          @report_urls = report_urls
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @request_uuid == other.request_uuid
          return false unless @status == other.status
          return false unless @report_urls == other.report_urls
          true
        end
      end
    end
  end
end
