# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared

      class State
        extend T::Sig
        include Crystalline::MetadataFields

        # The UUID of the EmployeeStateField this withholding applies to.
        field :employee_state_field_uuid, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('employee_state_field_uuid') } }
        # Override mode. Only `one_time` is currently exposed.
        field :override_type, Crystalline::Nilable.new(Models::Shared::PayrollEmployeeCompensationsTypeOverrideType), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('override_type'), 'decoder': ::GustoEmbedded::Utils.enum_from_string(Models::Shared::PayrollEmployeeCompensationsTypeOverrideType, true) } }
        # The amount that was withheld for this payroll.
        field :amount, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('amount') } }
        # How to interpret the amount.
        field :amount_type, Crystalline::Nilable.new(Models::Shared::PayrollEmployeeCompensationsTypeCustomWithholdingsAmountType), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('amount_type'), 'decoder': ::GustoEmbedded::Utils.enum_from_string(Models::Shared::PayrollEmployeeCompensationsTypeCustomWithholdingsAmountType, true) } }

        sig { params(employee_state_field_uuid: T.nilable(::String), override_type: T.nilable(Models::Shared::PayrollEmployeeCompensationsTypeOverrideType), amount: T.nilable(::String), amount_type: T.nilable(Models::Shared::PayrollEmployeeCompensationsTypeCustomWithholdingsAmountType)).void }
        def initialize(employee_state_field_uuid: nil, override_type: nil, amount: nil, amount_type: nil)
          @employee_state_field_uuid = employee_state_field_uuid
          @override_type = override_type
          @amount = amount
          @amount_type = amount_type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @employee_state_field_uuid == other.employee_state_field_uuid
          return false unless @override_type == other.override_type
          return false unless @amount == other.amount
          return false unless @amount_type == other.amount_type
          true
        end
      end
    end
  end
end
