# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared

      class TaxRequirementStatesList
        extend T::Sig
        include Crystalline::MetadataFields

        # One of the two-letter state abbreviations for the fifty United States and the District of Columbia (DC)
        field :state, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('state') } }
        # The current status of the state tax setup.
        # - `not_started`: No requirements have been filled
        # - `in_progress`: Some requirements have been filled, or default rates are applied
        # - `complete`: All requirements have been filled without default rates
        #
        field :setup_status, Crystalline::Nilable.new(Models::Shared::SetupStatus), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('setup_status'), 'decoder': ::GustoEmbedded::Utils.enum_from_string(Models::Shared::SetupStatus, true) } }
        # Whether the state is using system-assigned default SUI rates rather than employer-specific rates.
        field :default_rates_applied, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('default_rates_applied') } }
        # Whether the state tax setup is sufficiently complete for the company to run payroll.
        field :ready_to_run_payroll, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('ready_to_run_payroll') } }

        sig { params(state: T.nilable(::String), setup_status: T.nilable(Models::Shared::SetupStatus), default_rates_applied: T.nilable(T::Boolean), ready_to_run_payroll: T.nilable(T::Boolean)).void }
        def initialize(state: nil, setup_status: nil, default_rates_applied: nil, ready_to_run_payroll: nil)
          @state = state
          @setup_status = setup_status
          @default_rates_applied = default_rates_applied
          @ready_to_run_payroll = ready_to_run_payroll
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @state == other.state
          return false unless @setup_status == other.setup_status
          return false unless @default_rates_applied == other.default_rates_applied
          return false unless @ready_to_run_payroll == other.ready_to_run_payroll
          true
        end
      end
    end
  end
end
