# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Shared
      # TokenInfoType - The type of resource owner:
      # - `CompanyAdmin`: A company administrator
      # - `Employee`: An employee
      # - `Contractor`: A contractor
      #
      class TokenInfoType < T::Enum
        enums do
          COMPANY_ADMIN = new('CompanyAdmin')
          EMPLOYEE = new('Employee')
          CONTRACTOR = new('Contractor')
        end
      end
    end
  end
end
