# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared

      class ApplicableEarnings
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :earning_type,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("earning_type")}}
        )

        field(
          :earning_id,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("earning_id")}}
        )

        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("name")}}
        )

        field(
          :input_type,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("input_type")}}
        )

        field(
          :category,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("category")}}
        )

        sig {
          params(
            earning_type: T.nilable(::String),
            earning_id: T.nilable(::Float),
            name: T.nilable(::String),
            input_type: T.nilable(::String),
            category: T.nilable(::String)
          )
            .void
        }
        def initialize(earning_type: nil, earning_id: nil, name: nil, input_type: nil, category: nil)
          @earning_type = earning_type
          @earning_id = earning_id
          @name = name
          @input_type = input_type
          @category = category
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @earning_type == other.earning_type
          return false unless @earning_id == other.earning_id
          return false unless @name == other.name
          return false unless @input_type == other.input_type
          return false unless @category == other.category
          true
        end
      end
    end
  end
end
