# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared

      class DocumentType
        include ::Crystalline::Enum
        enums do
          USCIS_ALIEN_REGISTRATION_NUMBER = new("uscis_alien_registration_number")
          FORM_I94 = new("form_i94")
          FOREIGN_PASSPORT = new("foreign_passport")
        end

        open!
      end
    end
  end
end
