# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared
      # The representation of a time off request.
      class EmbeddedTimeOffRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The UUID of the time off request.
        field(
          :uuid,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("uuid"), required: true}}
        )
        # The status of the time off request.
        field(
          :status,
          Models::Shared::EmbeddedTimeOffRequestStatus,
          {
            'format_json': {
              'letter_case': ::GustoEmbedded::Utils.field_name("status"),
              required: true,
              'decoder': ::GustoEmbedded::Utils.open_enum_from_string(
                Models::Shared::EmbeddedTimeOffRequestStatus,
                false
              )
            }
          }
        )
        # An object where keys are dates in YYYY-MM-DD format and values are hours as string decimals (e.g. {"2025-01-20": "8.000"}).
        field(
          :days,
          Crystalline::Hash.new(Symbol, ::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("days"), required: true}}
        )

        field(
          :employee,
          Models::Shared::EmbeddedTimeOffRequestEmployee,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("employee"), required: true}}
        )
        # A note about the time off request, from the employee to the employer.
        field(
          :employee_note,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("employee_note"), required: true}}
        )
        # A note about the time off request, from the employer to the employee.
        field(
          :employer_note,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("employer_note"), required: true}}
        )
        # The type of the time off policy (e.g. vacation, sick).
        field(
          :policy_type,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("policy_type"), required: true}}
        )
        # The UUID of the time off policy associated with this request.
        field(
          :policy_uuid,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("policy_uuid"), required: true}}
        )

        field(
          :initiator,
          Crystalline::Nilable.new(Models::Shared::Initiator),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("initiator"), required: true}}
        )
        # This value will be null if the request has not been approved.
        field(
          :approver,
          Crystalline::Nilable.new(Models::Shared::Approver),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("approver"), required: true}}
        )

        sig {
          params(
            uuid: ::String,
            status: Models::Shared::EmbeddedTimeOffRequestStatus,
            days: T::Hash[Symbol, ::String],
            employee: Models::Shared::EmbeddedTimeOffRequestEmployee,
            employee_note: T.nilable(::String),
            employer_note: T.nilable(::String),
            policy_type: T.nilable(::String),
            policy_uuid: T.nilable(::String),
            initiator: T.nilable(Models::Shared::Initiator),
            approver: T.nilable(Models::Shared::Approver)
          )
            .void
        }
        def initialize(
          uuid:,
          status:,
          days:,
          employee:,
          employee_note: nil,
          employer_note: nil,
          policy_type: nil,
          policy_uuid: nil,
          initiator: nil,
          approver: nil
        )
          @uuid = uuid
          @status = status
          @days = days
          @employee = employee
          @employee_note = employee_note
          @employer_note = employer_note
          @policy_type = policy_type
          @policy_uuid = policy_uuid
          @initiator = initiator
          @approver = approver
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @uuid == other.uuid
          return false unless @status == other.status
          return false unless @days == other.days
          return false unless @employee == other.employee
          return false unless @employee_note == other.employee_note
          return false unless @employer_note == other.employer_note
          return false unless @policy_type == other.policy_type
          return false unless @policy_uuid == other.policy_uuid
          return false unless @initiator == other.initiator
          return false unless @approver == other.approver
          true
        end
      end
    end
  end
end
