# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared

      class EntityErrorObject
        extend T::Sig
        include Crystalline::MetadataFields

        # Specifies where the error occurs. Typically this key identifies the attribute/parameter related to the error.
        field(
          :error_key,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("error_key"), required: true}}
        )
        # Specifies the type of error. The category provides error groupings and can be used to build custom error handling in your integration. If category is `nested_errors`, the object will contain a nested `errors` property with entity errors.
        field(
          :category,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("category"), required: true}}
        )
        # Provides details about the error - generally this message can be surfaced to an end user.
        field(
          :message,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("message")}}
        )
        # Contains relevant data to identify the resource in question when applicable. For example, to identify an entity `entity_type` and `entity_uuid` will be provided.
        field(
          :metadata,
          Crystalline::Nilable.new(
            Crystalline::Union.new(Models::Shared::MetadataWithMultipleEntities, Models::Shared::MetadataWithOneEntity)
          ),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("metadata")}}
        )
        # Will only exist if category is `nested_errors`. It is possible to have multiple levels of nested errors.
        field(
          :errors,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::EntityErrorObject)),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("errors")}}
        )

        sig {
          params(
            error_key: ::String,
            category: ::String,
            message: T.nilable(::String),
            metadata: T.nilable(
              T.any(Models::Shared::MetadataWithMultipleEntities, Models::Shared::MetadataWithOneEntity)
            ),
            errors: T.nilable(T::Array[Models::Shared::EntityErrorObject])
          )
            .void
        }
        def initialize(error_key:, category:, message: nil, metadata: nil, errors: nil)
          @error_key = error_key
          @category = category
          @message = message
          @metadata = metadata
          @errors = errors
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @error_key == other.error_key
          return false unless @category == other.category
          return false unless @message == other.message
          return false unless @metadata == other.metadata
          return false unless @errors == other.errors
          true
        end
      end
    end
  end
end
