# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared

      class FederalTaxDetailsUpdate
        extend T::Sig
        include Crystalline::MetadataFields

        # The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
        field(
          :version,
          ::String,
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("version"), required: true}}
        )
        # The legal name of the company
        field(
          :legal_name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("legal_name")}}
        )
        # The company's Employer Identification Number (EIN). Must be 9 digits. Dashes are optional (e.g., '12-3456789' or '123456789').
        field(
          :ein,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("ein")}}
        )
        # What type of tax entity the company is. One of:
        # - C-Corporation
        # - S-Corporation
        # - Sole proprietor
        # - LLC
        # - LLP
        # - Limited partnership
        # - Co-ownership
        # - Association
        # - Trusteeship
        # - General partnership
        # - Joint venture
        # - Non-Profit
        field(
          :tax_payer_type,
          Crystalline::Nilable.new(Models::Shared::FederalTaxDetailsUpdateTaxPayerType),
          {
            'format_json': {
              'letter_case': ::GustoEmbedded::Utils.field_name("tax_payer_type"),
              'decoder': ::GustoEmbedded::Utils.enum_from_string(
                Models::Shared::FederalTaxDetailsUpdateTaxPayerType,
                true
              )
            }
          }
        )
        # The form used by the company for federal tax filing. One of:
        # - 941 (Quarterly federal tax return form)
        # - 944 (Annual federal tax return form)
        field(
          :filing_form,
          Crystalline::Nilable.new(Models::Shared::FederalTaxDetailsUpdateFilingForm),
          {
            'format_json': {
              'letter_case': ::GustoEmbedded::Utils.field_name("filing_form"),
              'decoder': ::GustoEmbedded::Utils.enum_from_string(
                Models::Shared::FederalTaxDetailsUpdateFilingForm,
                true
              )
            }
          }
        )
        # Whether the company is taxed as an S-Corporation
        field(
          :taxable_as_scorp,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("taxable_as_scorp")}}
        )

        sig {
          params(
            version: ::String,
            legal_name: T.nilable(::String),
            ein: T.nilable(::String),
            tax_payer_type: T.nilable(Models::Shared::FederalTaxDetailsUpdateTaxPayerType),
            filing_form: T.nilable(Models::Shared::FederalTaxDetailsUpdateFilingForm),
            taxable_as_scorp: T.nilable(T::Boolean)
          )
            .void
        }
        def initialize(
          version:,
          legal_name: nil,
          ein: nil,
          tax_payer_type: nil,
          filing_form: nil,
          taxable_as_scorp: nil
        )
          @version = version
          @legal_name = legal_name
          @ein = ein
          @tax_payer_type = tax_payer_type
          @filing_form = filing_form
          @taxable_as_scorp = taxable_as_scorp
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @version == other.version
          return false unless @legal_name == other.legal_name
          return false unless @ein == other.ein
          return false unless @tax_payer_type == other.tax_payer_type
          return false unless @filing_form == other.filing_form
          return false unless @taxable_as_scorp == other.taxable_as_scorp
          true
        end
      end
    end
  end
end
