# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared

      class FundingType
        include ::Crystalline::Enum
        enums do
          ACH = new("ach")
          REVERSE_WIRE = new("reverse_wire")
          WIRE_IN = new("wire_in")
          PARTNER_DISBURSEMENT = new("partner_disbursement")
          RTP = new("rtp")
          LINE_OF_CREDIT = new("line_of_credit")
        end

        open!
      end
    end
  end
end
