# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared
      # GeneratedDocumentStatus - Current status of the Generated Document
      class GeneratedDocumentStatus
        include ::Crystalline::Enum
        enums do
          PENDING = new("pending")
          STARTED = new("started")
          SUCCEEDED = new("succeeded")
          FAILED = new("failed")
        end

        open!
      end
    end
  end
end
