# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared
      # InformationRequestStatus - The status of the information request
      class InformationRequestStatus
        include ::Crystalline::Enum
        enums do
          PENDING_RESPONSE = new("pending_response")
          PENDING_REVIEW = new("pending_review")
          APPROVED = new("approved")
        end

        open!
      end
    end
  end
end
