# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared
      # Federal one-time custom withholding override.
      class PayrollUpdateFederal
        extend T::Sig
        include Crystalline::MetadataFields

        # Override mode. Only `one_time` is currently supported.
        field(
          :override_type,
          Crystalline::Nilable.new(Models::Shared::PayrollUpdateOverrideType),
          {
            'format_json': {
              'letter_case': ::GustoEmbedded::Utils.field_name("override_type"),
              'decoder': ::GustoEmbedded::Utils.enum_from_string(Models::Shared::PayrollUpdateOverrideType, true)
            }
          }
        )
        # The amount to be withheld for this payroll.
        field(
          :amount,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("amount")}}
        )
        # How to interpret the amount.
        field(
          :amount_type,
          Crystalline::Nilable.new(Models::Shared::PayrollUpdateEmployeeCompensationsAmountType),
          {
            'format_json': {
              'letter_case': ::GustoEmbedded::Utils.field_name("amount_type"),
              'decoder': ::GustoEmbedded::Utils.enum_from_string(
                Models::Shared::PayrollUpdateEmployeeCompensationsAmountType,
                true
              )
            }
          }
        )

        sig {
          params(
            override_type: T.nilable(Models::Shared::PayrollUpdateOverrideType),
            amount: T.nilable(::String),
            amount_type: T.nilable(Models::Shared::PayrollUpdateEmployeeCompensationsAmountType)
          )
            .void
        }
        def initialize(override_type: nil, amount: nil, amount_type: nil)
          @override_type = override_type
          @amount = amount
          @amount_type = amount_type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @override_type == other.override_type
          return false unless @amount == other.amount
          return false unless @amount_type == other.amount_type
          true
        end
      end
    end
  end
end
