# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared
      # PayrollEmployeeCompensationsTypeOverrideType - Override mode. Only `one_time` is currently exposed.
      class PayrollEmployeeCompensationsTypeOverrideType < T::Enum
        enums do
          ONE_TIME = new("one_time")
        end
      end
    end
  end
end
