# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared

      class PayrollUpdateEmployeeCompensations
        extend T::Sig
        include Crystalline::MetadataFields

        # The UUID of the employee.
        field(
          :employee_uuid,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("employee_uuid")}}
        )
        # The current version of this employee compensation from the prepared payroll. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
        field(
          :version,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("version")}}
        )
        # This employee will be excluded from payroll calculation and will not be paid for the payroll.
        field(
          :excluded,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("excluded")}}
        )
        # The employee's compensation payment method. Invalid values will be ignored.
        field(
          :payment_method,
          Crystalline::Nilable.new(Models::Shared::PayrollUpdatePaymentMethod),
          {
            'format_json': {
              'letter_case': ::GustoEmbedded::Utils.field_name("payment_method"),
              'decoder': ::GustoEmbedded::Utils.enum_from_string(Models::Shared::PayrollUpdatePaymentMethod, true)
            }
          }
        )
        # Custom text that will be printed as a personal note to the employee on a paystub.
        field(
          :memo,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("memo")}}
        )

        field(
          :fixed_compensations,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::PayrollUpdateFixedCompensations)),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("fixed_compensations")}}
        )

        field(
          :hourly_compensations,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::PayrollUpdateHourlyCompensations)),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("hourly_compensations")}}
        )

        field(
          :deductions,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::PayrollUpdateDeductions)),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("deductions")}}
        )
        # An array of all paid time off the employee is eligible for this pay period. Each paid time off object can be the name or the specific policy_uuid.
        field(
          :paid_time_off,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::PayrollUpdatePaidTimeOff)),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("paid_time_off")}}
        )
        # An array of reimbursements for the employee.
        field(
          :reimbursements,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::PayrollUpdateReimbursements)),
          {'format_json': {'letter_case': ::GustoEmbedded::Utils.field_name("reimbursements")}}
        )

        sig {
          params(
            employee_uuid: T.nilable(::String),
            version: T.nilable(::String),
            excluded: T.nilable(T::Boolean),
            payment_method: T.nilable(Models::Shared::PayrollUpdatePaymentMethod),
            memo: T.nilable(::String),
            fixed_compensations: T.nilable(T::Array[Models::Shared::PayrollUpdateFixedCompensations]),
            hourly_compensations: T.nilable(T::Array[Models::Shared::PayrollUpdateHourlyCompensations]),
            deductions: T.nilable(T::Array[Models::Shared::PayrollUpdateDeductions]),
            paid_time_off: T.nilable(T::Array[Models::Shared::PayrollUpdatePaidTimeOff]),
            reimbursements: T.nilable(T::Array[Models::Shared::PayrollUpdateReimbursements])
          )
            .void
        }
        def initialize(
          employee_uuid: nil,
          version: nil,
          excluded: nil,
          payment_method: nil,
          memo: nil,
          fixed_compensations: nil,
          hourly_compensations: nil,
          deductions: nil,
          paid_time_off: nil,
          reimbursements: nil
        )
          @employee_uuid = employee_uuid
          @version = version
          @excluded = excluded
          @payment_method = payment_method
          @memo = memo
          @fixed_compensations = fixed_compensations
          @hourly_compensations = hourly_compensations
          @deductions = deductions
          @paid_time_off = paid_time_off
          @reimbursements = reimbursements
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @employee_uuid == other.employee_uuid
          return false unless @version == other.version
          return false unless @excluded == other.excluded
          return false unless @payment_method == other.payment_method
          return false unless @memo == other.memo
          return false unless @fixed_compensations == other.fixed_compensations
          return false unless @hourly_compensations == other.hourly_compensations
          return false unless @deductions == other.deductions
          return false unless @paid_time_off == other.paid_time_off
          return false unless @reimbursements == other.reimbursements
          true
        end
      end
    end
  end
end
