# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared
      # PayrollUnprocessedEmployeeCompensationsTypePaymentMethod - The employee's compensation payment method. Is *only* `Historical` when retrieving external payrolls initially run outside of Gusto, then put into Gusto.
      class PayrollUnprocessedEmployeeCompensationsTypePaymentMethod
        include ::Crystalline::Enum
        enums do
          DIRECT_DEPOSIT = new("Direct Deposit")
          CHECK = new("Check")
          HISTORICAL = new("Historical")
        end

        open!
      end
    end
  end
end
