# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared
      # RecoveryCaseStatus - Status of the recovery case
      class RecoveryCaseStatus
        include ::Crystalline::Enum
        enums do
          OPEN = new("open")
          REDEBIT_INITIATED = new("redebit_initiated")
          WIRE_INITIATED = new("wire_initiated")
          RECOVERED = new("recovered")
          LOST = new("lost")
        end

        open!
      end
    end
  end
end
