# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module GustoEmbedded
  module Models
    module Shared
      # WebhookSubscriptionStatus - The status of the webhook subscription.
      class WebhookSubscriptionStatus
        include ::Crystalline::Enum
        enums do
          PENDING = new("pending")
          VERIFIED = new("verified")
          REMOVED = new("removed")
          UNREACHABLE = new("unreachable")
        end

        open!
      end
    end
  end
end
