# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'faraday'
require 'faraday/multipart'
require 'sorbet-runtime'

module OpenApiSDK
  extend T::Sig
  class ContractorPaymentMethod
    extend T::Sig


    sig { params(sdk_config: SDKConfiguration).void }
    def initialize(sdk_config)
      @sdk_configuration = sdk_config
    end


    sig { params(contractor_uuid: ::String, x_gusto_api_version: T.nilable(::OpenApiSDK::Shared::VersionHeader), request_body: T.nilable(::OpenApiSDK::Operations::PostV1ContractorsContractorUuidBankAccountsRequestBody)).returns(::OpenApiSDK::Operations::PostV1ContractorsContractorUuidBankAccountsResponse) }
    def create_bank_account(contractor_uuid, x_gusto_api_version = nil, request_body = nil)
      # create_bank_account - Create a contractor bank account
      # Creates a contractor bank account.
      # 
      # Note: We currently only support one bank account per contractor. Using this endpoint on a contractor who already has a bank account will just replace it.
      # 
      # scope: `contractor_payment_methods:write`
      request = ::OpenApiSDK::Operations::PostV1ContractorsContractorUuidBankAccountsRequest.new(
        
        contractor_uuid: contractor_uuid,
        x_gusto_api_version: x_gusto_api_version,
        request_body: request_body
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        ::OpenApiSDK::Operations::PostV1ContractorsContractorUuidBankAccountsRequest,
        base_url,
        '/v1/contractors/{contractor_uuid}/bank_accounts',
        request
      )
      headers = Utils.get_headers(request)
      req_content_type, data, form = Utils.serialize_request_body(request, :request_body, :json)
      headers['content-type'] = req_content_type
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      r = @sdk_configuration.client.post(url) do |req|
        req.headers = headers
        Utils.configure_request_security(req, @sdk_configuration.security) if !@sdk_configuration.nil? && !@sdk_configuration.security.nil?
        if form
          req.body = Utils.encode_form(form)
        elsif Utils.match_content_type(req_content_type, 'application/x-www-form-urlencoded')
          req.body = URI.encode_www_form(data)
        else
          req.body = data
        end
      end

      content_type = r.headers.fetch('Content-Type', 'application/octet-stream')

      res = ::OpenApiSDK::Operations::PostV1ContractorsContractorUuidBankAccountsResponse.new(
        status_code: r.status, content_type: content_type, raw_response: r
      )
      if r.status == 201
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Shared::ContractorBankAccount)
          res.contractor_bank_account = out
        end
      elsif r.status == 404
      elsif r.status == 422
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Shared::UnprocessableEntityErrorObject)
          res.unprocessable_entity_error_object = out
        end
      end

      res
    end


    sig { params(contractor_uuid: ::String, x_gusto_api_version: T.nilable(::OpenApiSDK::Shared::VersionHeader)).returns(::OpenApiSDK::Operations::GetV1ContractorsContractorUuidPaymentMethodResponse) }
    def get(contractor_uuid, x_gusto_api_version = nil)
      # get - Get a contractor's payment method
      # Fetches a contractor's payment method. A contractor payment method
      # describes how the payment should be split across the contractor's associated
      # bank accounts.
      # 
      # scope: `contractor_payment_methods:read`
      request = ::OpenApiSDK::Operations::GetV1ContractorsContractorUuidPaymentMethodRequest.new(
        
        contractor_uuid: contractor_uuid,
        x_gusto_api_version: x_gusto_api_version
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        ::OpenApiSDK::Operations::GetV1ContractorsContractorUuidPaymentMethodRequest,
        base_url,
        '/v1/contractors/{contractor_uuid}/payment_method',
        request
      )
      headers = Utils.get_headers(request)
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      r = @sdk_configuration.client.get(url) do |req|
        req.headers = headers
        Utils.configure_request_security(req, @sdk_configuration.security) if !@sdk_configuration.nil? && !@sdk_configuration.security.nil?
      end

      content_type = r.headers.fetch('Content-Type', 'application/octet-stream')

      res = ::OpenApiSDK::Operations::GetV1ContractorsContractorUuidPaymentMethodResponse.new(
        status_code: r.status, content_type: content_type, raw_response: r
      )
      if r.status == 200
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Shared::ContractorPaymentMethod)
          res.contractor_payment_method = out
        end
      elsif r.status == 404
      end

      res
    end


    sig { params(contractor_uuid: ::String, x_gusto_api_version: T.nilable(::OpenApiSDK::Shared::VersionHeader), request_body: T.nilable(::OpenApiSDK::Operations::PutV1ContractorsContractorIdPaymentMethodRequestBody)).returns(::OpenApiSDK::Operations::PutV1ContractorsContractorIdPaymentMethodResponse) }
    def update(contractor_uuid, x_gusto_api_version = nil, request_body = nil)
      # update - Update a contractor's payment method
      # Updates a contractor's payment method. Note that creating a contractor
      # bank account will also update the contractor's payment method.
      # 
      # scope: `contractor_payment_methods:write`
      request = ::OpenApiSDK::Operations::PutV1ContractorsContractorIdPaymentMethodRequest.new(
        
        contractor_uuid: contractor_uuid,
        x_gusto_api_version: x_gusto_api_version,
        request_body: request_body
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        ::OpenApiSDK::Operations::PutV1ContractorsContractorIdPaymentMethodRequest,
        base_url,
        '/v1/contractors/{contractor_uuid}/payment_method',
        request
      )
      headers = Utils.get_headers(request)
      req_content_type, data, form = Utils.serialize_request_body(request, :request_body, :json)
      headers['content-type'] = req_content_type
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      r = @sdk_configuration.client.put(url) do |req|
        req.headers = headers
        Utils.configure_request_security(req, @sdk_configuration.security) if !@sdk_configuration.nil? && !@sdk_configuration.security.nil?
        if form
          req.body = Utils.encode_form(form)
        elsif Utils.match_content_type(req_content_type, 'application/x-www-form-urlencoded')
          req.body = URI.encode_www_form(data)
        else
          req.body = data
        end
      end

      content_type = r.headers.fetch('Content-Type', 'application/octet-stream')

      res = ::OpenApiSDK::Operations::PutV1ContractorsContractorIdPaymentMethodResponse.new(
        status_code: r.status, content_type: content_type, raw_response: r
      )
      if r.status == 200
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Shared::ContractorPaymentMethod)
          res.contractor_payment_method = out
        end
      elsif r.status == 404
      elsif r.status == 422
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Shared::UnprocessableEntityErrorObject)
          res.unprocessable_entity_error_object = out
        end
      end

      res
    end
  end
end
