# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Operations
  

    class DeleteV1JobsJobIdRequest < ::Crystalline::FieldAugmented
      extend T::Sig

      # The UUID of the job
      field :job_id, ::String, { 'path_param': { 'field_name': 'job_id', 'style': 'simple', 'explode': false } }
      # Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
      field :x_gusto_api_version, T.nilable(::GustoEmbedded::Shared::VersionHeader), { 'header': { 'field_name': 'X-Gusto-API-Version', 'style': 'simple', 'explode': false } }


      sig { params(job_id: ::String, x_gusto_api_version: T.nilable(::GustoEmbedded::Shared::VersionHeader)).void }
      def initialize(job_id: nil, x_gusto_api_version: nil)
        @job_id = job_id
        @x_gusto_api_version = x_gusto_api_version
      end
    end
  end
end
