# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Operations
    

      class GetV1PaymentReceiptsPayrollsPayrollUuidResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # successful
        field :payroll_receipt, Crystalline::Nilable.new(Models::Shared::PayrollReceipt)

        sig { params(content_type: ::String, status_code: ::Integer, raw_response: ::Faraday::Response, payroll_receipt: T.nilable(Models::Shared::PayrollReceipt)).void }
        def initialize(content_type:, status_code:, raw_response:, payroll_receipt: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @payroll_receipt = payroll_receipt
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @payroll_receipt == other.payroll_receipt
          true
        end
      end
    end
  end
end
