# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Operations
    

      class PostDepartmentsRequestBody
        extend T::Sig
        include Crystalline::MetadataFields


        field :title, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('title') } }

        sig { params(title: T.nilable(::String)).void }
        def initialize(title: nil)
          @title = title
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @title == other.title
          true
        end
      end
    end
  end
end
