# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Operations
  

    class PostV1EmployeesEmployeeIdWorkAddressesRequestBody < ::Crystalline::FieldAugmented
      extend T::Sig

      # Date the employee began working at the company location
      field :effective_date, T.nilable(::Date), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('effective_date'), 'decoder': Utils.date_from_iso_format(true) } }
      # Reference to a company location
      field :location_uuid, T.nilable(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('location_uuid') } }


      sig { params(effective_date: T.nilable(::Date), location_uuid: T.nilable(::String)).void }
      def initialize(effective_date: nil, location_uuid: nil)
        @effective_date = effective_date
        @location_uuid = location_uuid
      end
    end
  end
end
