# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Operations
  

    class PostV1EmployeesEmployeeIdGarnishmentsRequestBody < ::Crystalline::FieldAugmented
      extend T::Sig

      # The amount of the garnishment. Either a percentage or a fixed dollar amount. Represented as a float, e.g. "8.00".
      field :amount, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('amount') } }
      # Whether the garnishment is court ordered.
      field :court_ordered, T::Boolean, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('court_ordered') } }
      # Whether or not this garnishment is currently active.
      field :active, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('active') } }
      # The maximum deduction per annum. A null value indicates no maximum. Represented as a float, e.g. "200.00".
      field :annual_maximum, T.nilable(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('annual_maximum') } }
      # Additional child support order details
      field :child_support, T.nilable(::GustoEmbedded::Shared::GarnishmentChildSupport), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('child_support') } }
      # Whether the amount should be treated as a percentage to be deducted per pay period.
      field :deduct_as_percentage, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('deduct_as_percentage') } }
      # The description of the garnishment.
      field :description, T.nilable(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('description') } }
      # The specific type of garnishment for court ordered garnishments.
      field :garnishment_type, T.nilable(::GustoEmbedded::Operations::GarnishmentType), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('garnishment_type'), 'decoder': Utils.enum_from_string(::GustoEmbedded::Operations::GarnishmentType, true) } }
      # The maximum deduction per pay period. A null value indicates no maximum. Represented as a float, e.g. "16.00".
      field :pay_period_maximum, T.nilable(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('pay_period_maximum') } }
      # Whether the garnishment should recur indefinitely.
      field :recurring, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('recurring') } }
      # The number of times to apply the garnishment. Ignored if recurring is true.
      field :times, T.nilable(::Integer), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('times') } }
      # A maximum total deduction for the lifetime of this garnishment. A null value indicates no maximum.
      field :total_amount, T.nilable(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('total_amount') } }


      sig { params(amount: ::String, court_ordered: T::Boolean, active: T.nilable(T::Boolean), annual_maximum: T.nilable(::String), child_support: T.nilable(::GustoEmbedded::Shared::GarnishmentChildSupport), deduct_as_percentage: T.nilable(T::Boolean), description: T.nilable(::String), garnishment_type: T.nilable(::GustoEmbedded::Operations::GarnishmentType), pay_period_maximum: T.nilable(::String), recurring: T.nilable(T::Boolean), times: T.nilable(::Integer), total_amount: T.nilable(::String)).void }
      def initialize(amount: nil, court_ordered: nil, active: nil, annual_maximum: nil, child_support: nil, deduct_as_percentage: nil, description: nil, garnishment_type: nil, pay_period_maximum: nil, recurring: nil, times: nil, total_amount: nil)
        @amount = amount
        @court_ordered = court_ordered
        @active = active
        @annual_maximum = annual_maximum
        @child_support = child_support
        @deduct_as_percentage = deduct_as_percentage
        @description = description
        @garnishment_type = garnishment_type
        @pay_period_maximum = pay_period_maximum
        @recurring = recurring
        @times = times
        @total_amount = total_amount
      end
    end
  end
end
