# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Operations

      class PutV1EmployeesRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
        field :version, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('version'), required: true } }

        field :first_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('first_name') } }

        field :last_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('last_name') } }

        field :email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('email') } }

        field :work_email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('work_email') } }

        field :date_of_birth, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('date_of_birth') } }

        field :ssn, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('ssn') } }
        # Whether the employee is a two percent shareholder of the company. This field only applies to companies with an S-Corp entity type.
        field :two_percent_shareholder, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('two_percent_shareholder') } }

        field :middle_initial, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('middle_initial') } }

        field :preferred_first_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('preferred_first_name') } }

        sig { params(version: ::String, first_name: T.nilable(::String), last_name: T.nilable(::String), email: T.nilable(::String), work_email: T.nilable(::String), date_of_birth: T.nilable(::String), ssn: T.nilable(::String), two_percent_shareholder: T.nilable(T::Boolean), middle_initial: T.nilable(::String), preferred_first_name: T.nilable(::String)).void }
        def initialize(version:, first_name: nil, last_name: nil, email: nil, work_email: nil, date_of_birth: nil, ssn: nil, two_percent_shareholder: nil, middle_initial: nil, preferred_first_name: nil)
          @version = version
          @first_name = first_name
          @last_name = last_name
          @email = email
          @work_email = work_email
          @date_of_birth = date_of_birth
          @ssn = ssn
          @two_percent_shareholder = two_percent_shareholder
          @middle_initial = middle_initial
          @preferred_first_name = preferred_first_name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @version == other.version
          return false unless @first_name == other.first_name
          return false unless @last_name == other.last_name
          return false unless @email == other.email
          return false unless @work_email == other.work_email
          return false unless @date_of_birth == other.date_of_birth
          return false unless @ssn == other.ssn
          return false unless @two_percent_shareholder == other.two_percent_shareholder
          return false unless @middle_initial == other.middle_initial
          return false unless @preferred_first_name == other.preferred_first_name
          true
        end
      end
    end
  end
end
