# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Operations

      class PutV1EmployeeFormSignRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The UUID of the employee
        field :employee_id, ::String, { 'path_param': { 'field_name': 'employee_id', 'style': 'simple', 'explode': false } }
        # The UUID of the form
        field :form_id, ::String, { 'path_param': { 'field_name': 'form_id', 'style': 'simple', 'explode': false } }

        field :request_body, Models::Operations::PutV1EmployeeFormSignRequestBody, { 'request': { 'media_type': 'application/json' } }
        # Optional header to supply the IP address. This can be used to supply the IP address for signature endpoints instead of the signed_by_ip_address parameter.
        field :x_gusto_client_ip, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'x-gusto-client-ip', 'style': 'simple', 'explode': false } }
        # Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
        field :x_gusto_api_version, Crystalline::Nilable.new(Models::Operations::PutV1EmployeeFormSignHeaderXGustoAPIVersion), { 'header': { 'field_name': 'X-Gusto-API-Version', 'style': 'simple', 'explode': false } }

        sig { params(employee_id: ::String, form_id: ::String, request_body: Models::Operations::PutV1EmployeeFormSignRequestBody, x_gusto_client_ip: T.nilable(::String), x_gusto_api_version: T.nilable(Models::Operations::PutV1EmployeeFormSignHeaderXGustoAPIVersion)).void }
        def initialize(employee_id:, form_id:, request_body:, x_gusto_client_ip: nil, x_gusto_api_version: Models::Operations::PutV1EmployeeFormSignHeaderXGustoAPIVersion::TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_06_MINUS_15)
          @employee_id = employee_id
          @form_id = form_id
          @request_body = request_body
          @x_gusto_client_ip = x_gusto_client_ip
          @x_gusto_api_version = x_gusto_api_version
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @employee_id == other.employee_id
          return false unless @form_id == other.form_id
          return false unless @request_body == other.request_body
          return false unless @x_gusto_client_ip == other.x_gusto_client_ip
          return false unless @x_gusto_api_version == other.x_gusto_api_version
          true
        end
      end
    end
  end
end
