# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Operations
      # PutV1EmployeesEmployeeIdPaymentMethodType - The payment method type. If type is Check, split_by and splits do not need to be populated. If type is Direct Deposit, split_by and splits are required.
      class PutV1EmployeesEmployeeIdPaymentMethodType < T::Enum
        enums do
          CHECK = new('Check')
          DIRECT_DEPOSIT = new('Direct Deposit')
        end
      end
    end
  end
end
