# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Operations
  

    class PutV1CompanyBenefitsCompanyBenefitIdContributionExclusionsRequestBody < ::Crystalline::FieldAugmented
      extend T::Sig

      # The list of contribution exclusions to update
      field :contribution_exclusions, T::Array[::GustoEmbedded::Shared::ContributionExclusion], { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('contribution_exclusions') } }


      sig { params(contribution_exclusions: T::Array[::GustoEmbedded::Shared::ContributionExclusion]).void }
      def initialize(contribution_exclusions: nil)
        @contribution_exclusions = contribution_exclusions
      end
    end
  end
end
