# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Operations
  
    # Information for the user who will be the primary payroll administrator for the new company.
    class User < ::Crystalline::FieldAugmented
      extend T::Sig

      # The email of the user who will be the primary payroll admin.
      field :email, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('email') } }
      # The first name of the user who will be the primary payroll admin.
      field :first_name, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('first_name') } }
      # The last name of the user who will be the primary payroll admin.
      field :last_name, ::String, { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('last_name') } }
      # The phone number of the user who will be the primary payroll admin.
      field :phone, T.nilable(::String), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('phone') } }


      sig { params(email: ::String, first_name: ::String, last_name: ::String, phone: T.nilable(::String)).void }
      def initialize(email: nil, first_name: nil, last_name: nil, phone: nil)
        @email = email
        @first_name = first_name
        @last_name = last_name
        @phone = phone
      end
    end
  end
end
