# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class EmployeeCheckNumberMapping < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The check number for the relevant employee
      field :check_number, T.nilable(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('check_number') } }
      # The UUID for an employee
      field :employee_uuid, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('employee_uuid') } }


      sig { params(check_number: T.nilable(::Float), employee_uuid: T.nilable(::String)).void }
      def initialize(check_number: nil, employee_uuid: nil)
        @check_number = check_number
        @employee_uuid = employee_uuid
      end
    end
  end
end
