# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class PostV1SandboxGenerate1099RequestBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The contractor UUID.
      field :contractor_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('contractor_id') } }
      # Must be equal to or more recent than 2015. If not specified, defaults to the previous year.
      # 
      field :year, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('year') } }


      sig { params(contractor_id: ::String, year: T.nilable(::Integer)).void }
      def initialize(contractor_id: nil, year: nil)
        @contractor_id = contractor_id
        @year = year
      end
    end
  end
end
