# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module GustoEmbedded
  module Models
    module Errors
    

      class GetCompaniesCompanyUuidContractorPaymentsPreviewErrors
        extend T::Sig
        include Crystalline::MetadataFields


        field :base, Crystalline::Nilable.new(Crystalline::Array.new(Models::Errors::GetCompaniesCompanyUuidContractorPaymentsPreviewBase)), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('base') } }

        field :check_date, Crystalline::Nilable.new(Crystalline::Array.new(Models::Errors::CheckDate)), { 'format_json': { 'letter_case': ::GustoEmbedded::Utils.field_name('check_date') } }

        sig { params(base: T.nilable(T::Array[Models::Errors::GetCompaniesCompanyUuidContractorPaymentsPreviewBase]), check_date: T.nilable(T::Array[Models::Errors::CheckDate])).void }
        def initialize(base: nil, check_date: nil)
          @base = base
          @check_date = check_date
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @base == other.base
          return false unless @check_date == other.check_date
          true
        end
      end
    end
  end
end
