workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    GustoEmbedded-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/Gusto/Gusto-Partner-API/refs/heads/ar/add-generated-openapi-spec-to-repo/generated/embedded/api.v2024-04-01.embedded.yaml
              authHeader: Authorization
              authSecret: $openapi_doc_auth_token
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/gusto/ruby-sdk/gusto-embedded-oas
targets:
    gusto-embedded:
        target: ruby
        source: GustoEmbedded-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gusto/ruby-sdk/gusto-embedded-oas-code-samples
            labelOverride:
                fixedValue: Ruby (SDK)
            blocking: false
